### ISSUE TITLE
How to enable fold3d?

### ISSUE THREAD

**Issue by lucasleesw** [hku-systems/fold3d#1]
Hello, thanks for the great repo.
Could you share how to enable fold3D in GPT models?
Do you know if it is enabled by default? Should I use the additional options such as  `use_new_schedule` ?

**Comment by fanxinli** [comment]
Thanks for your interest in Fold3D.
To enable Fold3D, you need to add arguments use-new-schedule and overlap-data-parallel-allreduce to original scripts of Megatron-LM.
